import { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { toast } from "react-toastify";
import { Toaster } from "sonner";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import Header from "@/layout/DefaultLayout/Header/Header";
import Footer from "@/layout/DefaultLayout/Footer/Footer";
import { LucidProvider } from "@/context/providers/LucidProvider";
import SmartContractProvider from "@/context/providers/SmartContractProvider";
import Backgrounds from "@/components/Background";

// Sử dụng font Poppins với nhiều trọng lượng
const poppinsFont = Poppins({
  weight: ['100', '400', '500', '600', '900'],
  subsets: ['latin'],
  variable: '--font-poppins', // Tạo biến CSS cho font
});

// Metadata cho trang
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout dựa trên vai trò của người dùng
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${poppinsFont.variable} antialiased`}>
        <TooltipProvider>
          <LucidProvider>
            <SmartContractProvider>
              <Backgrounds>
              <Header />
                <div id="main" className="bg-transparent">
                  <div>{children}</div>
                </div>
                <Footer />
              </Backgrounds>
              <Toaster />
            </SmartContractProvider>
          </LucidProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
